global:
  resolve_timeout: 3m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 10m
  receiver: 'email-notify'

receivers:
- name: 'email-notify'
  email_configs:
  - to: "2482315781@qq.com"
    from: "2482315781@qq.com"
    smarthost: 'smtp.qq.com:587'
    auth_username: "2482315781@qq.com"
    auth_password: "lcmziuiwkyyeecca"
    send_resolved: true
    require_tls: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname','instance']
